services:
  app:
    image: alexandertolchinsky/devops-for-programmers-project-lvl1
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c 'sleep 3 && npm test'
    depends_on:
      - "db"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres 
