on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: make ci
      - uses: docker/login-action@v2
        with:
          username: alexandertolchinsky
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: alexandertolchinsky/devops-for-programmers-project-lvl1
